---
abstract: 'Expose all public methods of classes as RPC methods'
author:
  - 'Sherwin Daganato <sherwin@daganato.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-RPC-Dispatcher-ClassMapping
no_index:
  directory:
    - t
    - inc
requires:
  JSON::RPC::Dispatcher: 0.0505
  Moose: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/sherwind/JSON-RPC-Dispatcher-ClassMapping/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/sherwind/JSON-RPC-Dispatcher-ClassMapping.git
version: 0.03
